#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ngx_http_enhanced_memcached_module
Version  : b58a4500db3c4ee274be54a18abc767219dcfd36
Release  : 25
URL      : https://github.com/bpaquet/ngx_http_enhanced_memcached_module/archive/b58a4500db3c4ee274be54a18abc767219dcfd36.tar.gz
Source0  : https://github.com/bpaquet/ngx_http_enhanced_memcached_module/archive/b58a4500db3c4ee274be54a18abc767219dcfd36.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: ngx_http_enhanced_memcached_module-lib = %{version}-%{release}
BuildRequires : buildreq-nginx
BuildRequires : openssl-dev

%description
# Enhanced Nginx Memcached Module
[![Build Status](https://travis-ci.org/bpaquet/ngx_http_enhanced_memcached_module.png)](https://travis-ci.org/bpaquet/ngx_http_enhanced_memcached_module)

%package lib
Summary: lib components for the ngx_http_enhanced_memcached_module package.
Group: Libraries

%description lib
lib components for the ngx_http_enhanced_memcached_module package.


%prep
%setup -q -n ngx_http_enhanced_memcached_module-b58a4500db3c4ee274be54a18abc767219dcfd36
cd %{_builddir}/ngx_http_enhanced_memcached_module-b58a4500db3c4ee274be54a18abc767219dcfd36

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
nginx-module configure
nginx-module build

%install
nginx-module install %{buildroot}


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/nginx-mainline/ngx_http_enhanced_memcached_module.so
